# Generated by Django 5.2.1 on 2025-05-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=50, null=True, verbose_name='naam')),
                ('leeftijd', models.CharField(choices=[('basisschool', '6-8'), ('onderbouw', '9-12'), ('mavo', '13-14'), ('havo', '2011-2015')])),
                ('niveau', models.CharField(choices=[('basisschool', 'basis'), ('onderbouw', 'onderbouw'), ('mavo', 'mavo'), ('havo', 'havo'), ('vmbo', 'vmbo')], default='Onbekend', max_length=30, null=True)),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='email')),
                ('telefoon', models.CharField(max_length=30, null=True, verbose_name='telefoon')),
                ('akkoord', models.BooleanField(default=False)),
                ('training', models.CharField(choices=[('basisschool', 'Faalangst'), ('onderbouw', 'Leer leren'), ('mavo', 'Remedial Teaching'), ('havo', 'Nederlands')], default='Onbekend', max_length=30, null=True)),
                ('volgorde', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['volgorde'],
            },
        ),
    ]
