# Generated by Django 5.2.1 on 2025-07-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chelping', '0003_alter_contact_leeftijd_alter_contact_niveau_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interesse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leeftijd', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='contact',
            name='leeftijd',
        ),
        migrations.CreateModel(
            name='gebruiker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leeftijd', models.CharField(max_length=100)),
                ('interesses', models.ManyToManyField(to='chelping.interesse')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='interesses',
            field=models.ManyToManyField(to='chelping.interesse'),
        ),
    ]
