# Generated by Django 5.2.1 on 2025-07-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chelping', '0004_interesse_remove_contact_leeftijd_gebruiker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='leeftijd',
            field=models.CharField(default=8, max_length=100),
        ),
    ]
