# Generated by Django 5.2.1 on 2025-07-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chelping', '0005_contact_leeftijd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interesse',
            name='leeftijd',
            field=models.CharField(choices=[('0', 'basisschool'), ('1', 'vmbo'), ('2', 'havo'), ('3', 'vwo')], max_length=100),
        ),
    ]
