# Generated by Django 5.2.1 on 2025-07-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chelping', '0006_alter_interesse_leeftijd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='interesses',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='niveau',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='training',
        ),
        migrations.AlterField(
            model_name='contact',
            name='leeftijd',
            field=models.CharField(max_length=50, null=True, verbose_name='leeftijd'),
        ),
        migrations.DeleteModel(
            name='gebruiker',
        ),
        migrations.DeleteModel(
            name='Interesse',
        ),
    ]
