# Generated by Django 5.1.7 on 2025-07-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chelping', '0007_remove_contact_interesses_remove_contact_niveau_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='niveau',
            field=models.CharField(choices=[('Basisschool', [('0', 'groep 3'), ('1', 'groep 4'), ('2', 'groep 5'), ('3', 'groep 6'), ('4', 'groep 7'), ('5', 'groep 8')]), ('Vmbo', [('0', 'basis'), ('1', 'kader'), ('2', 'mavo')]), ('Havo', [('0', '1e klas'), ('1', '2e klas')]), ('Vwo', [('0', '1e klas')])], default='niveau', max_length=50),
        ),
        migrations.AddField(
            model_name='contact',
            name='training',
            field=models.CharField(choices=[('KM', 'Kennismakingsgesprek'), ('RT', 'Remidial teaching'), ('LL', 'Leer Leren')], default='training', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='leeftijd',
            field=models.CharField(choices=[('10', '10 jaar'), ('11', '11 jaar'), ('12', '12 jaar')], default='leeftijd', max_length=50, null=True),
        ),
    ]
